LiDAROdometer:
  NDT:
    # minimum transformation difference for termination condition
    TRANS_EPSILON: 0.001
    # maximum step size for More-Thuente line search
    # If the carrier moves fast, increase the value
    STEP_SIZE: 0.1
    # Resolution of NDT grid structure (VoxelGridCovariance)
    # If the carrier moves fast, increase the value
    RESOLUTION: 2.0
    # max number of registration iterations
    MAX_ITERATIONS: 50
  AVGFilter:
    # Approximate Voxel Grid leaf size
    LEAF_SIZE: [ 0.5, 0.5, 0.5 ]
  # update map only when the distance is bigger than the 'UpdateMapThd', unit: Meter
  UpdateMapThd: 2.0
